@extends('admin.layouts.app')

@section('title', 'Generated Documents')

@section('breadcrumb')
    <li class="breadcrumb-item active">Generated Documents</li>
@endsection

@section('content')
<div class="container-fluid">
    <!-- Page Header -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h1 class="h3 mb-0">Generated Documents</h1>
            <p class="text-muted mb-0">View and manage all generated letters and forms</p>
        </div>
        <a href="{{ route('admin.generated-documents.create') }}" class="btn btn-primary">
            <i class="fas fa-plus me-2"></i>Generate New Document
        </a>
    </div>

    <!-- Filters -->
    <div class="card border-0 shadow-sm mb-4">
        <div class="card-body">
            <form action="{{ route('admin.generated-documents.index') }}" method="GET" class="row g-3">
                <div class="col-md-3">
                    <label class="form-label">Search</label>
                    <input type="text" name="search" class="form-control"
                           placeholder="Search by title or patient..." value="{{ request('search') }}">
                </div>
                <div class="col-md-2">
                    <label class="form-label">Status</label>
                    <select name="status" class="form-select">
                        <option value="">All Status</option>
                        <option value="draft" {{ request('status') === 'draft' ? 'selected' : '' }}>Draft</option>
                        <option value="final" {{ request('status') === 'final' ? 'selected' : '' }}>Final</option>
                        <option value="sent" {{ request('status') === 'sent' ? 'selected' : '' }}>Sent</option>
                        <option value="void" {{ request('status') === 'void' ? 'selected' : '' }}>Void</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Template</label>
                    <select name="template_id" class="form-select">
                        <option value="">All Templates</option>
                        @php
                            $templateList = \App\Models\Template::visibleTo(auth()->user())->orderBy('name')->get();
                        @endphp
                        @foreach($templateList as $tpl)
                            <option value="{{ $tpl->id }}" {{ request('template_id') == $tpl->id ? 'selected' : '' }}>
                                {{ $tpl->name }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-4 d-flex align-items-end gap-2">
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-search me-1"></i>Filter
                    </button>
                    <a href="{{ route('admin.generated-documents.index') }}" class="btn btn-outline-secondary">
                        <i class="fas fa-times me-1"></i>Clear
                    </a>
                </div>
            </form>
        </div>
    </div>

    <!-- Alert Messages -->
    @if(session('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="fas fa-check-circle me-2"></i>{{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    @endif

    @if(session('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <i class="fas fa-exclamation-circle me-2"></i>{{ session('error') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    @endif

    <!-- Documents Table -->
    <div class="card border-0 shadow-sm">
        <div class="card-body p-0">
            @if($documents->count() > 0)
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead class="table-light">
                            <tr>
                                <th>Document</th>
                                <th>Patient</th>
                                <th>Template</th>
                                <th>Status</th>
                                <th>Generated By</th>
                                <th>Date</th>
                                <th class="text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($documents as $document)
                                <tr>
                                    <td>
                                        <a href="{{ route('admin.generated-documents.show', $document) }}"
                                           class="text-decoration-none fw-bold">
                                            {{ $document->title }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ route('admin.patients.show', $document->patient) }}"
                                           class="text-decoration-none">
                                            {{ $document->patient->full_name ?? $document->patient->first_name . ' ' . $document->patient->last_name }}
                                        </a>
                                        <small class="text-muted d-block">
                                            {{ $document->patient->patient_id ?? 'ID: ' . $document->patient->id }}
                                        </small>
                                    </td>
                                    <td>
                                        <span class="badge {{ $document->template->type_badge_class ?? 'bg-secondary' }}">
                                            {{ ucfirst($document->template->type ?? 'Unknown') }}
                                        </span>
                                        <small class="text-muted d-block">{{ $document->template->name ?? 'Unknown' }}</small>
                                    </td>
                                    <td>
                                        <span class="badge {{ $document->status_badge_class }}">
                                            {{ $document->status_label }}
                                        </span>
                                        @if($document->sent_at)
                                            <small class="text-muted d-block">
                                                Sent: {{ formatDateUk($document->sent_at) }}
                                            </small>
                                        @endif
                                    </td>
                                    <td>{{ $document->generator->name ?? 'Unknown' }}</td>
                                    <td>
                                        {{ formatDateUk($document->created_at) }}
                                        <small class="text-muted d-block">{{ $document->created_at->format('H:i') }}</small>
                                    </td>
                                    <td class="text-end">
                                        <div class="btn-group">
                                            <a href="{{ route('admin.generated-documents.show', $document) }}"
                                               class="btn btn-sm btn-outline-primary" title="View">
                                                <i class="fas fa-eye"></i>
                                            </a>
                                            @can('download', $document)
                                                <a href="{{ route('admin.generated-documents.download', $document) }}"
                                                   class="btn btn-sm btn-outline-success" title="Download PDF">
                                                    <i class="fas fa-download"></i>
                                                </a>
                                            @endcan
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle"
                                                        data-bs-toggle="dropdown">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </button>
                                                <ul class="dropdown-menu dropdown-menu-end">
                                                    @can('send', $document)
                                                        <li>
                                                            <a class="dropdown-item" href="{{ route('admin.generated-documents.send-form', $document) }}">
                                                                <i class="fas fa-envelope me-2"></i>Send via Email
                                                            </a>
                                                        </li>
                                                    @endcan
                                                    @can('finalize', $document)
                                                        <li>
                                                            <form action="{{ route('admin.generated-documents.finalize', $document) }}" method="POST">
                                                                @csrf
                                                                @method('PATCH')
                                                                <button type="submit" class="dropdown-item">
                                                                    <i class="fas fa-check me-2"></i>Finalize
                                                                </button>
                                                            </form>
                                                        </li>
                                                    @endcan
                                                    @can('void', $document)
                                                        <li><hr class="dropdown-divider"></li>
                                                        <li>
                                                            <form action="{{ route('admin.generated-documents.void', $document) }}" method="POST"
                                                                  onsubmit="return confirm('Are you sure you want to void this document?')">
                                                                @csrf
                                                                @method('PATCH')
                                                                <button type="submit" class="dropdown-item text-danger">
                                                                    <i class="fas fa-ban me-2"></i>Void
                                                                </button>
                                                            </form>
                                                        </li>
                                                    @endcan
                                                    @can('delete', $document)
                                                        <li>
                                                            <form action="{{ route('admin.generated-documents.destroy', $document) }}" method="POST"
                                                                  onsubmit="return confirm('Are you sure you want to delete this document?')">
                                                                @csrf
                                                                @method('DELETE')
                                                                <button type="submit" class="dropdown-item text-danger">
                                                                    <i class="fas fa-trash me-2"></i>Delete
                                                                </button>
                                                            </form>
                                                        </li>
                                                    @endcan
                                                </ul>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                <!-- Pagination -->
                <div class="card-footer bg-white">
                    {{ $documents->links() }}
                </div>
            @else
                <div class="text-center py-5">
                    <i class="fas fa-file-pdf fa-3x text-muted mb-3"></i>
                    <h5>No documents found</h5>
                    <p class="text-muted">
                        @if(request()->hasAny(['search', 'status', 'template_id']))
                            Try adjusting your filters or search criteria.
                        @else
                            Generate your first document from a template.
                        @endif
                    </p>
                    <a href="{{ route('admin.generated-documents.create') }}" class="btn btn-primary">
                        <i class="fas fa-plus me-2"></i>Generate New Document
                    </a>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection
