<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Consultations Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0;
            color: #7f8c8d;
        }
        .summary {
            background-color: #f8f9fa;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .summary-row {
            display: table;
            width: 100%;
            margin-bottom: 10px;
        }
        .summary-label {
            display: table-cell;
            font-weight: bold;
            width: 200px;
        }
        .summary-value {
            display: table-cell;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #34495e;
            color: white;
            padding: 10px;
            text-align: left;
            border: 1px solid #2c3e50;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #7f8c8d;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Consultations Report</h1>
        <p>Generated on: {{ \Carbon\Carbon::now()->format('F d, Y h:i A') }}</p>
        <p>Period: {{ \Carbon\Carbon::parse($startDate)->format('F d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('F d, Y') }}</p>
        @if($department)
        <p>Clinic: {{ $department->name }}</p>
        @endif
    </div>

    <div class="summary">
        <div class="summary-row">
            <div class="summary-label">Total Consultations:</div>
            <div class="summary-value">{{ number_format($summary['total_consultations']) }}</div>
        </div>
        <div class="summary-row">
            <div class="summary-label">Total Duration:</div>
            <div class="summary-value">{{ number_format($summary['total_duration_hours'], 2) }} hours</div>
        </div>
        <div class="summary-row">
            <div class="summary-label">Average Duration:</div>
            <div class="summary-value">{{ number_format($summary['average_duration_minutes'], 2) }} minutes</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Clinic/Department</th>
                <th class="text-right">Consultations</th>
                <th class="text-right">Total Duration (Hours)</th>
                <th class="text-right">Total Duration (Minutes)</th>
                <th class="text-right">Average Duration (Minutes)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData as $monthData)
            <tr>
                <td>{{ $monthData->month_name }}</td>
                <td>{{ $monthData->department_name }}</td>
                <td class="text-right">{{ number_format($monthData->total_consultations) }}</td>
                <td class="text-right">{{ number_format($monthData->total_duration_hours, 2) }}</td>
                <td class="text-right">{{ number_format($monthData->total_duration_minutes) }}</td>
                <td class="text-right">{{ number_format($monthData->average_duration_minutes, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated by {{ config('app.name', 'EHR System') }}</p>
    </div>
</body>
</html>

