<?php

namespace App\Http\Controllers;

use App\Models\Setting;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ThemeController extends Controller
{
    /**
     * Generate dynamic CSS based on current theme settings
     */
    public function dynamicCss()
    {
        try {
            // Check if application is installed
            if (!\Illuminate\Support\Facades\File::exists(storage_path('installed'))) {
                // Return default colors if not installed
                $primaryColor = '#007bff';
                $secondaryColor = '#6c757d';
            } else {
                // Get current theme colors from settings
                $primaryColor = Setting::get('primary_color', '#007bff');
                $secondaryColor = Setting::get('secondary_color', '#6c757d');
            }
            
            // Generate CSS content with dynamic colors
            $css = $this->generateDynamicCss($primaryColor, $secondaryColor);
            
            // Return CSS response with proper headers
            return response($css, 200, [
                'Content-Type' => 'text/css',
                'Cache-Control' => 'no-cache, no-store, must-revalidate', // No caching for dynamic updates
                'Pragma' => 'no-cache',
                'Expires' => '0',
            ]);
        } catch (\Exception $e) {
            // Return default CSS if there's any error
            $css = $this->generateDynamicCss('#007bff', '#6c757d');
            return response($css, 200, [
                'Content-Type' => 'text/css',
                'Cache-Control' => 'no-cache, no-store, must-revalidate',
                'Pragma' => 'no-cache',
                'Expires' => '0',
            ]);
        }
    }
    
    /**
     * Generate the CSS content with dynamic colors
     */
    private function generateDynamicCss($primaryColor, $secondaryColor)
    {
        // Calculate additional colors based on primary and secondary
        $primaryLight = $this->lightenColor($primaryColor, 20);
        $secondaryDark = $this->darkenColor($secondaryColor, 20);
        
        return "
/* Dynamic Theme Colors - Generated by PHP */
/* This file is dynamically generated based on admin settings */

:root {
    --primary-color: {$primaryColor};
    --secondary-color: {$secondaryColor};
    --primary-light: {$primaryLight};
    --secondary-dark: {$secondaryDark};
    --primary-gradient: linear-gradient(135deg, {$primaryColor} 0%, {$primaryLight} 100%);
    --accent-color: #FF6B35;
    --accent-light: #FF8E53;
    --gold-color: #F7931E;
    --success-color: #28A745;
    --warning-color: #ffc107;
    --danger-color: #dc3545;
    --info-color: #17a2b8;
    --text-light: #ffffff;
    --text-dark: #2C3E50;
    --text-muted: #6c757d;
    --bg-light: #F8FAFB;
    --shadow-light: rgba(0, 0, 0, 0.08);
    --shadow-medium: rgba(0, 0, 0, 0.15);
    --shadow-heavy: rgba(0, 0, 0, 0.25);
}

/* Primary color applications */
.btn-primary, 
.bg-primary {
    background: var(--primary-color) !important;
    border-color: var(--primary-color) !important;
}

.btn-primary:hover {
    background: var(--primary-light) !important;
    border-color: var(--primary-light) !important;
}

.text-primary {
    color: var(--primary-color) !important;
}

.border-primary {
    border-color: var(--primary-color) !important;
}

/* Secondary color applications */
.btn-secondary,
.bg-secondary {
    background: var(--secondary-color) !important;
    border-color: var(--secondary-color) !important;
}

.text-secondary {
    color: var(--secondary-color) !important;
}

.border-secondary {
    border-color: var(--secondary-color) !important;
}

/* Button outline variants */
.btn-outline-primary {
    color: var(--primary-color) !important;
    border-color: var(--primary-color) !important;
}

.btn-outline-primary:hover,
.btn-outline-primary:focus,
.btn-outline-primary:active {
    background: var(--primary-color) !important;
    border-color: var(--primary-color) !important;
    color: white !important;
}

.btn-outline-secondary {
    color: var(--secondary-color) !important;
    border-color: var(--secondary-color) !important;
}

.btn-outline-secondary:hover,
.btn-outline-secondary:focus,
.btn-outline-secondary:active {
    background: var(--secondary-color) !important;
    border-color: var(--secondary-color) !important;
    color: white !important;
}

/* Navigation styling */
/* For light navbar with white background */
.navbar-light .navbar-brand {
    color: var(--primary-color) !important;
}

.navbar-light .navbar-nav .nav-link {
    color: var(--text-dark) !important;
    transition: color 0.3s ease;
}

.navbar-light .navbar-nav .nav-link:hover,
.navbar-light .navbar-nav .nav-link:focus {
    color: var(--primary-color) !important;
}

.navbar-light .navbar-nav .nav-link.active {
    color: var(--primary-color) !important;
    font-weight: 500;
}

/* For dark navbar with primary background */
.navbar-dark .navbar-brand,
.bg-primary .navbar-brand {
    color: var(--text-light) !important;
}

.navbar-dark .navbar-nav .nav-link,
.bg-primary .navbar-nav .nav-link {
    color: var(--text-light) !important;
    transition: color 0.3s ease;
}

.navbar-dark .navbar-nav .nav-link:hover,
.navbar-dark .navbar-nav .nav-link:focus,
.bg-primary .navbar-nav .nav-link:hover,
.bg-primary .navbar-nav .nav-link:focus {
    color: var(--accent-color) !important;
}

/* Navbar toggler for light navbar */
.navbar-light .navbar-toggler {
    border-color: rgba(0,0,0,.1);
}

.navbar-light .navbar-toggler:focus {
    box-shadow: 0 0 0 0.25rem rgba(0, 123, 255, 0.25);
}

/* Hero section */
.hero-section {
    background: var(--primary-gradient) !important;
}

/* Footer */
.footer,
.bg-dark {
    background: var(--secondary-color) !important;
}

/* Cards and sections */
.section-title {
    color: var(--primary-color) !important;
}

.card-header {
    background-color: var(--bg-light) !important;
    border-bottom: 1px solid var(--secondary-color) !important;
}

/* Links */
a {
    color: var(--primary-color);
    transition: color 0.3s ease;
}

a:hover,
a:focus {
    color: var(--primary-light);
    text-decoration: none;
}

/* Form elements */
.form-control:focus {
    border-color: var(--primary-color);
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
}

.form-select:focus {
    border-color: var(--primary-color);
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
}

/* Progress bars */
.progress-bar {
    background-color: var(--primary-color) !important;
}

/* Badges */
.badge-primary,
.badge.bg-primary {
    background-color: var(--primary-color) !important;
}

.badge-secondary,
.badge.bg-secondary {
    background-color: var(--secondary-color) !important;
}

/* Alerts */
.alert-primary {
    color: var(--primary-color);
    background-color: rgba(0, 123, 255, 0.1);
    border-color: var(--primary-color);
}

/* Tables */
.table-primary {
    background-color: rgba(0, 123, 255, 0.1);
}

.table-hover tbody tr:hover {
    background-color: rgba(0, 123, 255, 0.05);
}

/* Custom components */
.feature-icon {
    color: var(--primary-color) !important;
}

.service-card:hover {
    border-color: var(--primary-color) !important;
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1) !important;
}

.doctor-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15) !important;
}

/* Pagination */
.page-link {
    color: var(--primary-color);
}

.page-link:hover {
    color: var(--primary-light);
    background-color: var(--bg-light);
    border-color: var(--primary-color);
}

.page-item.active .page-link {
    background-color: var(--primary-color);
    border-color: var(--primary-color);
}

/* Breadcrumb */
.breadcrumb-item + .breadcrumb-item::before {
    color: var(--secondary-color);
}

.breadcrumb-item.active {
    color: var(--primary-color);
}

/* Custom utilities */
.text-gradient {
    background: var(--primary-gradient);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

.bg-gradient-primary {
    background: var(--primary-gradient) !important;
}

/* Responsive adjustments */
@media (max-width: 768px) {
    .hero-section {
        background: var(--primary-color) !important;
    }
}

/* Animation effects */
@keyframes primaryPulse {
    0% {
        box-shadow: 0 0 0 0 rgba(0, 123, 255, 0.7);
    }
    70% {
        box-shadow: 0 0 0 10px rgba(0, 123, 255, 0);
    }
    100% {
        box-shadow: 0 0 0 0 rgba(0, 123, 255, 0);
    }
}

.pulse-primary {
    animation: primaryPulse 2s infinite;
}
";
    }
    
    /**
     * Lighten a hex color by a percentage
     */
    private function lightenColor($hex, $percent)
    {
        // Remove # if present
        $hex = ltrim($hex, '#');
        
        // Convert hex to RGB
        $r = hexdec(substr($hex, 0, 2));
        $g = hexdec(substr($hex, 2, 2));
        $b = hexdec(substr($hex, 4, 2));
        
        // Lighten each component
        $r = min(255, $r + ($percent / 100) * (255 - $r));
        $g = min(255, $g + ($percent / 100) * (255 - $g));
        $b = min(255, $b + ($percent / 100) * (255 - $b));
        
        // Convert back to hex
        return '#' . sprintf('%02x%02x%02x', round($r), round($g), round($b));
    }
    
    /**
     * Darken a hex color by a percentage
     */
    private function darkenColor($hex, $percent)
    {
        // Remove # if present
        $hex = ltrim($hex, '#');
        
        // Convert hex to RGB
        $r = hexdec(substr($hex, 0, 2));
        $g = hexdec(substr($hex, 2, 2));
        $b = hexdec(substr($hex, 4, 2));
        
        // Darken each component
        $r = max(0, $r - ($percent / 100) * $r);
        $g = max(0, $g - ($percent / 100) * $g);
        $b = max(0, $b - ($percent / 100) * $b);
        
        // Convert back to hex
        return '#' . sprintf('%02x%02x%02x', round($r), round($g), round($b));
    }
}
