<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;

class GeneratedDocument extends Model
{
    use HasFactory;

    protected $fillable = [
        'template_id',
        'patient_id',
        'file_path',
        'file_name',
        'title',
        'rendered_content',
        'status',
        'generated_by',
        'sent_at',
        'sent_to',
        'notes',
    ];

    protected $casts = [
        'sent_at' => 'datetime',
    ];

    public const STATUS_DRAFT = 'draft';
    public const STATUS_FINAL = 'final';
    public const STATUS_SENT = 'sent';
    public const STATUS_VOID = 'void';

    /**
     * Get the template used for this document.
     */
    public function template(): BelongsTo
    {
        return $this->belongsTo(Template::class);
    }

    /**
     * Get the patient this document belongs to.
     */
    public function patient(): BelongsTo
    {
        return $this->belongsTo(Patient::class);
    }

    /**
     * Get the user who generated this document.
     */
    public function generator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    /**
     * Scope to filter by status.
     */
    public function scopeOfStatus($query, string $status)
    {
        return $query->where('status', $status);
    }

    /**
     * Scope to filter draft documents.
     */
    public function scopeDraft($query)
    {
        return $query->where('status', self::STATUS_DRAFT);
    }

    /**
     * Scope to filter final documents.
     */
    public function scopeFinal($query)
    {
        return $query->where('status', self::STATUS_FINAL);
    }

    /**
     * Scope to filter sent documents.
     */
    public function scopeSent($query)
    {
        return $query->where('status', self::STATUS_SENT);
    }

    /**
     * Scope to filter documents for a patient.
     */
    public function scopeForPatient($query, $patientId)
    {
        return $query->where('patient_id', $patientId);
    }

    /**
     * Scope: Documents generated by a user.
     * Doctors see only their own generated documents.
     * Admins see all.
     */
    public function scopeGeneratedBy($query, User $user)
    {
        if ($user->is_admin || $user->role === 'admin') {
            return $query;
        }

        return $query->where('generated_by', $user->id);
    }

    /**
     * Check if document is draft.
     */
    public function isDraft(): bool
    {
        return $this->status === self::STATUS_DRAFT;
    }

    /**
     * Check if document is final.
     */
    public function isFinal(): bool
    {
        return $this->status === self::STATUS_FINAL;
    }

    /**
     * Check if document has been sent.
     */
    public function isSent(): bool
    {
        return $this->status === self::STATUS_SENT;
    }

    /**
     * Check if document is void.
     */
    public function isVoid(): bool
    {
        return $this->status === self::STATUS_VOID;
    }

    /**
     * Mark document as final.
     */
    public function markAsFinal(): bool
    {
        return $this->update(['status' => self::STATUS_FINAL]);
    }

    /**
     * Mark document as sent.
     */
    public function markAsSent(string $email): bool
    {
        return $this->update([
            'status' => self::STATUS_SENT,
            'sent_at' => now(),
            'sent_to' => $email,
        ]);
    }

    /**
     * Void the document.
     */
    public function void(): bool
    {
        return $this->update(['status' => self::STATUS_VOID]);
    }

    /**
     * Check if PDF file exists.
     */
    public function pdfExists(): bool
    {
        return $this->file_path && Storage::disk('private')->exists($this->file_path);
    }

    /**
     * Get full path to PDF file.
     */
    public function getFullPdfPath(): ?string
    {
        if (!$this->file_path) {
            return null;
        }

        return Storage::disk('private')->path($this->file_path);
    }

    /**
     * Get download URL (signed for security).
     */
    public function getDownloadUrl(): ?string
    {
        if (!$this->pdfExists()) {
            return null;
        }

        return route('admin.generated-documents.download', $this);
    }

    /**
     * Get status badge class for display.
     */
    public function getStatusBadgeClassAttribute(): string
    {
        return match ($this->status) {
            self::STATUS_DRAFT => 'bg-secondary',
            self::STATUS_FINAL => 'bg-primary',
            self::STATUS_SENT => 'bg-success',
            self::STATUS_VOID => 'bg-danger',
            default => 'bg-secondary',
        };
    }

    /**
     * Get status label for display.
     */
    public function getStatusLabelAttribute(): string
    {
        return ucfirst($this->status);
    }

    /**
     * Delete the PDF file when document is deleted.
     */
    protected static function booted(): void
    {
        static::deleting(function (GeneratedDocument $document) {
            if ($document->file_path && Storage::disk('private')->exists($document->file_path)) {
                Storage::disk('private')->delete($document->file_path);
            }
        });
    }
}
